wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1697884877.896485
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.10.12
      5: 0.15.12
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
episode_timeout:
  desc: null
  value: 30
fps_limit:
  desc: null
  value: 18
learning_rate:
  desc: null
  value: 0.0003
steps_per_update:
  desc: null
  value: 512
entropy_coefficient:
  desc: null
  value: 0.001
total_timesteps:
  desc: null
  value: 100000
num_actions:
  desc: null
  value: 5
model_name:
  desc: null
  value: qwop_model_v09
notes:
  desc: null
  value: Reward switching long presses of wo and qp
